#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pexpect
Version  : 4.2.0
Release  : 19
URL      : http://pypi.debian.net/pexpect/pexpect-4.2.0.tar.gz
Source0  : http://pypi.debian.net/pexpect/pexpect-4.2.0.tar.gz
Summary  : Pexpect allows easy control of interactive console applications.
Group    : Development/Tools
License  : ISC
Requires: pexpect-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
The best way to run these tests is from the directory above this one. Run:
py.test

%package python
Summary: python components for the pexpect package.
Group: Default

%description python
python components for the pexpect package.


%prep
%setup -q -n pexpect-4.2.0

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
